### ISSUE TITLE
 Add support for NeoLine

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/panel-fs-neo-org#144]
## Is your feature request related to a problem? Please describe.

I'm always frustrated when we can't work with wallets supported by https://governance.neo.org/

## Describe the solution you'd like

Research NeoLine and what's needed to support it.

**Comment by roman-khimov** [comment]
We knew this already, but just for the reference here: https://neoline.io/dapi/N3.html
`signMessage` is the good old magic-prefix thing, problematic for us.

**Comment by mike-petrov** [comment]
As for [NeoLine](https://neoline.io/), there are mobile application and chrome extension:

**Chrome extension**
- no app connection function, but it works with governance.neo.org because use local wc route

**IOS**
- no app connection function, but have Discover with `N3 Governance` dapp, thats why I think dapp have a web socket with local API

<img width="200" alt="image" src="https://github.com/nspcc-dev/panel-fs-neo-org/assets/32885629/310de3b1-1794-4f95-8200-be6f7de182f1">
